theme = "catppuccin_mocha"

[editor]
rulers = [120]

[editor.indent-guides]
render = true
character = "▏"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
j = { k = "normal_mode" }

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]
