fpath+=("$(brew --prefix)/share/zsh/site-functions")

autoload -U promptinit; promptinit

# change the path color
# zstyle :prompt:pure:path color red

prompt pure


alias nv="nvim"


# Some tmux-related shell aliases

# Attaches tmux to the last session; creates a new session if none exists.
alias t='tmux attach || tmux new-session'

# Attaches tmux to a session (example: ta portal)
alias ta='tmux attach -t'

# Creates a new session
alias tn='tmux new-session'

# Lists all ongoing sessions
alias tl='tmux list-sessions'
export PATH="/opt/homebrew/bin:$PATH"
export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"; [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Docker aliases
alias dim='docker images'
alias db='docker build .'

# Customize to your needs...
export PATH=$HOME/.rbenv/bin:/usr/local/bin:$HOME/.bin:$PATH

# load rbenv automatically
eval "$(rbenv init - zsh)"
