alias nv="nvim"
export PS1="%~ $ "


# Some tmux-related shell aliases

# Attaches tmux to the last session; creates a new session if none exists.
alias t='tmux attach || tmux new-session'

# Attaches tmux to a session (example: ta portal)
alias ta='tmux attach -t'

# Creates a new session
alias tn='tmux new-session'

# Lists all ongoing sessions
alias tl='tmux list-sessions'
export PATH="/opt/homebrew/bin:$PATH"
export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"; [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Go stuff
export GOPATH="$HOME/go"
export PATH=$PATH:$GOPATH/bin
# Docker aliases
alias dim='docker images'
alias db='docker build .'

# Customize to your needs...
export PATH=$HOME/.rbenv/bin:/usr/local/bin:$HOME/.bin:$PATH

source <(fzf --zsh)

# load rbenv automatically
eval "$(rbenv init - zsh)"
